### PR TITLE
Retry to add Finnish translation

### LINKED ISSUE #22: Add Finnish translation
### Checklist

- [X] I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
- [X] This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
- [X] This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
- [X] This idea is not already possible.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

Adding Finnish translation for the app would allow Finnish people to use it more easily

### Solution

I am able to add the translation

### Why are the currently avialable solutions not sufficient?

Finnish is currently missing

### Can you help us with this feature request?

Yes, I can code the solution myself and send a merge request.

### Additional information

This is the first time I come across a template like this, I hope I did ok!
Happy Hacktoberfest! I was browsing topics under translation for a soft start of the season and this project seemed like a nice one to start with if you are participating this year.

### PR DESCRIPTION
**Pull request by minna-xD**
I'm a little scared to do this 😅 but luckily you're able to review it first.
Hope I got it right this time..? (Sorry for the hassle! I should've just gone on the website to enter these translations and looked for a different PR opportunity.)

Closes #22

### CODE REVIEW

**Review by Abrynos — APPROVED** [review]

**Comment by Abrynos** [comment]
It's fine 😄 No worries! 

> Sorry for the hassle!

I'm happy to receive merge requests. It's not a hassle at all!

I've also shot digital ocean as the event organizer a message on twitter in the hope, that it won't get counted as an invalid merge request for you!

**Comment by Abrynos** [comment]
CI runs without failing now also. Very nice. Thanks for all your help!

**Comment by minna-xD** [comment]
Thank you so much! For everything 🙂

**Comment by Abrynos** [comment]
Thanks you for your contribution 🏆

**Pull request merged**
